using Class_biz__information_schema;
using Class_biz_accounts;
using Class_biz_agencies;
using Class_biz_agency_satellite_stations;
using Class_biz_availabilities;
using Class_biz_capcode_unit_maps;
using Class_biz_care_skill_ratings;
using Class_biz_care_skills;
using Class_biz_chassis_makes;
using Class_biz_chassis_models;
using Class_biz_cities;
using Class_biz_crew_shift_vehicles;
using Class_biz_crews;
using Class_biz_custom_makes;
using Class_biz_custom_models;
using Class_biz_donations;
using Class_biz_driver_skill_ratings;
using Class_biz_driver_skills;
using Class_biz_efficipay_dockets;
using Class_biz_efficipay_tokens;
using Class_biz_enrollment;
using Class_biz_ephemeral_dispatches;
using Class_biz_eval_statuses;
using Class_biz_evals;
using Class_biz_field_situations;
using Class_biz_fleetman;
using Class_biz_fuels;
using Class_biz_fund_drives;
using Class_biz_gripes;
using Class_biz_incident_nature_translations;
using Class_biz_incident_natures;
using Class_biz_indicator_median_length_of_service;
using Class_biz_indicator_monthly_vehicles_up_and_current;
using Class_biz_indicator_shiftwise_vehicles_up_and_current;
using Class_biz_leave;
using Class_biz_leaves;
using Class_biz_love_letter_batches;
using Class_biz_manifest;
using Class_biz_medical_aspirational_phases;
using Class_biz_medical_release_levels;
using Class_biz_members;
using Class_biz_milestones;
using Class_biz_notifications;
using Class_biz_oscalert_logs;
using Class_biz_patient_age_units;
using Class_biz_patient_encounter_levels;
using Class_biz_patient_encounters;
using Class_biz_post_cardinalities;
using Class_biz_privileges;
using Class_biz_publicity;
using Class_biz_quick_messages;
using Class_biz_radio_dispatches;
using Class_biz_rank_groups;
using Class_biz_ranks;
using Class_biz_residents;
using Class_biz_role_member_map;
using Class_biz_role_member_map_logs;
using Class_biz_role_notification_map;
using Class_biz_role_privilege_map;
using Class_biz_roles;
using Class_biz_scenes_reached_distributor;
using Class_biz_schedule_assignment_logs;
using Class_biz_schedule_assignments;
using Class_biz_scheduled_tasks;
using Class_biz_scheduling;
using Class_biz_sections;
using Class_biz_shifts;
using Class_biz_skill_ratings;
using Class_biz_sms_gateways;
using Class_biz_states;
using Class_biz_streets;
using Class_biz_subjoined_attributes;
using Class_biz_tapouts;
using Class_biz_tiers;
using Class_biz_trespasses;
using Class_biz_uniform_catalogs;
using Class_biz_uniform_classes;
using Class_biz_uniform_option_categories;
using Class_biz_uniform_piece_colors;
using Class_biz_uniform_piece_makes;
using Class_biz_uniform_piece_models;
using Class_biz_uniform_piece_vendors;
using Class_biz_uniform_pieces;
using Class_biz_uniform_priorities;
using Class_biz_user;
using Class_biz_user_member_map;
using Class_biz_users;
using Class_biz_vehicle_down_natures;
using Class_biz_vehicle_kinds;
using Class_biz_vehicle_quarters;
using Class_biz_vehicle_quarters_history;
using Class_biz_vehicle_usability_history;
using Class_biz_vehicles;
using Class_db__information_schema;
using Class_db_accounts;
using Class_db_agencies;
using Class_db_agency_satellite_stations;
using Class_db_availabilities;
using Class_db_capcode_unit_maps;
using Class_db_care_skill_ratings;
using Class_db_care_skills;
using Class_db_chassis_makes;
using Class_db_chassis_models;
using Class_db_cities;
using Class_db_crew_shift_vehicles;
using Class_db_custom_makes;
using Class_db_custom_models;
using Class_db_data_conditions;
using Class_db_donations;
using Class_db_driver_skill_ratings;
using Class_db_driver_skills;
using Class_db_efficipay_dockets;
using Class_db_efficipay_tokens;
using Class_db_enrollment;
using Class_db_ephemeral_dispatches;
using Class_db_eval_statuses;
using Class_db_evals;
using Class_db_field_situations;
using Class_db_fuels;
using Class_db_gripes;
using Class_db_incident_nature_translations;
using Class_db_incident_natures;
using Class_db_indicator_median_length_of_service;
using Class_db_indicator_monthly_vehicles_up_and_current;
using Class_db_indicator_shiftwise_vehicles_up_and_current;
using Class_db_leaves;
using Class_db_love_letter_batches;
using Class_db_manifest;
using Class_db_medical_aspirational_phases;
using Class_db_medical_release_levels;
using Class_db_members;
using Class_db_milestones;
using Class_db_notifications;
using Class_db_oscalert_logs;
using Class_db_patient_age_units;
using Class_db_patient_encounter_levels;
using Class_db_patient_encounters;
using Class_db_post_cardinalities;
using Class_db_privileges;
using Class_db_radio_dispatches;
using Class_db_rank_groups;
using Class_db_ranks;
using Class_db_residents;
using Class_db_role_member_map;
using Class_db_role_member_map_logs;
using Class_db_role_notification_map;
using Class_db_role_privilege_map;
using Class_db_roles;
using Class_db_scenes_reached;
using Class_db_schedule_assignment_logs;
using Class_db_schedule_assignments;
using Class_db_shifts;
using Class_db_skill_ratings;
using Class_db_sms_gateways;
using Class_db_states;
using Class_db_streets;
using Class_db_subjoined_attributes;
using Class_db_tapouts;
using Class_db_tiers;
using Class_db_trail;
using Class_db_trespasses;
using Class_db_uniform_catalogs;
using Class_db_uniform_classes;
using Class_db_uniform_option_categories;
using Class_db_uniform_piece_colors;
using Class_db_uniform_piece_makes;
using Class_db_uniform_piece_models;
using Class_db_uniform_piece_vendors;
using Class_db_uniform_pieces;
using Class_db_uniform_priorities;
using Class_db_user;
using Class_db_user_member_map;
using Class_db_users;
using Class_db_vehicle_down_natures;
using Class_db_vehicle_kinds;
using Class_db_vehicle_quarters;
using Class_db_vehicle_quarters_history;
using Class_db_vehicle_usability_history;
using Class_db_vehicles;
using Class_dbhomedb_trail;
using Class_dbkeyclick_trail;
using System;
using System.Security.Claims;

namespace OscarDotNet.Engine.Di
  {
  public partial class Biz
    {

    private readonly Func<ClaimsIdentity> userClaimsIdentityFn;
    //
    private readonly Lazy<TClass_biz__information_schema> _information_schema__provisioner;
    private readonly Lazy<TClass_biz_accounts> accounts__provisioner;
    private readonly Lazy<TClass_biz_agencies> agencies__provisioner;
    private readonly Lazy<TClass_biz_agency_satellite_stations> agency_satellite_stations__provisioner;
    private readonly Lazy<TClass_biz_availabilities> availabilities__provisioner;
    private readonly Lazy<TClass_biz_capcode_unit_maps> capcode_unit_maps__provisioner;
    private readonly Lazy<TClass_biz_care_skills> care_skills__provisioner;
    private readonly Lazy<TClass_biz_care_skill_ratings> care_skill_ratings__provisioner;
    private readonly Lazy<TClass_biz_chassis_makes> chassis_makes__provisioner;
    private readonly Lazy<TClass_biz_chassis_models> chassis_models__provisioner;
    private readonly Lazy<TClass_biz_cities> cities__provisioner;
    private readonly Lazy<TClass_biz_crew_shift_vehicles> crew_shift_vehicles__provisioner;
    private readonly Lazy<TClass_biz_crews> crews__provisioner;
    private readonly Lazy<TClass_biz_custom_makes> custom_makes__provisioner;
    private readonly Lazy<TClass_biz_custom_models> custom_models__provisioner;
    private readonly Lazy<TClass_biz_donations> donations__provisioner;
    private readonly Lazy<TClass_biz_driver_skills> driver_skills__provisioner;
    private readonly Lazy<TClass_biz_driver_skill_ratings> driver_skill_ratings__provisioner;
    private readonly Lazy<TClass_biz_efficipay_dockets> efficipay_dockets__provisioner;
    private readonly Lazy<TClass_biz_efficipay_tokens> efficipay_tokens__provisioner;
    private readonly Lazy<TClass_biz_enrollment> enrollment__provisioner;
    private readonly Lazy<TClass_biz_ephemeral_dispatches> ephemeral_dispatches__provisioner;
    private readonly Lazy<TClass_biz_evals> evals__provisioner;
    private readonly Lazy<TClass_biz_eval_statuses> eval_statuses__provisioner;
    private readonly Lazy<TClass_biz_field_situations> field_situations__provisioner;
    private readonly Lazy<TClass_biz_fleetman> fleetman__provisioner;
    private readonly Lazy<TClass_biz_fuels> fuels__provisioner;
    private readonly Lazy<TClass_biz_fund_drives> fund_drives__provisioner;
    private readonly Lazy<TClass_biz_gripes> gripes__provisioner;
    private readonly Lazy<TClass_biz_incident_nature_translations> incident_nature_translations__provisioner;
    private readonly Lazy<TClass_biz_incident_natures> incident_natures__provisioner;
    private readonly Lazy<TClass_biz_indicator_median_length_of_service> indicator_median_length_of_service__provisioner;
    private readonly Lazy<TClass_biz_indicator_monthly_vehicles_up_and_current> indicator_monthly_vehicles_up_and_current__provisioner;
    private readonly Lazy<TClass_biz_indicator_shiftwise_vehicles_up_and_current> indicator_shiftwise_vehicles_up_and_current__provisioner;
    private readonly Lazy<TClass_biz_leave> leave__provisioner;
    private readonly Lazy<TClass_biz_leaves> leaves__provisioner;
    private readonly Lazy<TClass_biz_love_letter_batches> love_letter_batches__provisioner;
    private readonly Lazy<TClass_biz_manifest> manifest__provisioner;
    private readonly Lazy<TClass_biz_medical_aspirational_phases> medical_aspirational_phases__provisioner;
    private readonly Lazy<TClass_biz_medical_release_levels> medical_release_levels__provisioner;
    private readonly Lazy<TClass_biz_members> members__provisioner;
    private readonly Lazy<TClass_biz_milestones> milestones__provisioner;
    private readonly Lazy<TClass_biz_notifications> notifications__provisioner;
    private readonly Lazy<TClass_biz_oscalert_logs> oscalert_logs__provisioner;
    private readonly Lazy<TClass_biz_patient_age_units> patient_age_units__provisioner;
    private readonly Lazy<TClass_biz_patient_encounters> patient_encounters__provisioner;
    private readonly Lazy<TClass_biz_patient_encounter_levels> patient_encounter_levels__provisioner;
    private readonly Lazy<TClass_biz_post_cardinalities> post_cardinalities__provisioner;
    private readonly Lazy<TClass_biz_privileges> privileges__provisioner;
    private readonly Lazy<TClass_biz_publicity> publicity__provisioner;
    private readonly Lazy<TClass_biz_quick_messages> quick_messages__provisioner;
    private readonly Lazy<TClass_biz_ranks> ranks__provisioner;
    private readonly Lazy<TClass_biz_rank_groups> rank_groups__provisioner;
    private readonly Lazy<TClass_biz_radio_dispatches> radio_dispatches__provisioner;
    private readonly Lazy<TClass_biz_residents> residents__provisioner;
    private readonly Lazy<TClass_biz_roles> roles__provisioner;
    private readonly Lazy<TClass_biz_role_member_map> role_member_map__provisioner;
    private readonly Lazy<TClass_biz_role_member_map_logs> role_member_map_logs__provisioner;
    private readonly Lazy<TClass_biz_role_notification_map> role_notification_map__provisioner;
    private readonly Lazy<TClass_biz_role_privilege_map> role_privilege_map__provisioner;
    private readonly Lazy<TClass_biz_scenes_reached_distributor> scenes_reached_distributor__provisioner;
    private readonly Lazy<TClass_biz_scheduled_tasks> scheduled_tasks__provisioner;
    private readonly Lazy<TClass_biz_schedule_assignments> schedule_assignments__provisioner;
    private readonly Lazy<TClass_biz_schedule_assignment_logs> schedule_assignment_logs__provisioner;
    private readonly Lazy<TClass_biz_scheduling> scheduling__provisioner;
    private readonly Lazy<TClass_biz_sections> sections__provisioner;
    private readonly Lazy<TClass_biz_shifts> shifts__provisioner;
    private readonly Lazy<TClass_biz_skill_ratings> skill_ratings__provisioner;
    private readonly Lazy<TClass_biz_sms_gateways> sms_gateways__provisioner;
    private readonly Lazy<TClass_biz_states> states__provisioner;
    private readonly Lazy<TClass_biz_streets> streets__provisioner;
    private readonly Lazy<TClass_biz_subjoined_attributes> subjoined_attributes__provisioner;
    private readonly Lazy<TClass_biz_tapouts> tapouts__provisioner;
    private readonly Lazy<TClass_biz_tiers> tiers__provisioner;
    private readonly Lazy<TClass_biz_trespasses> trespasses__provisioner;
    private readonly Lazy<TClass_biz_uniform_catalogs> uniform_catalogs__provisioner;
    private readonly Lazy<TClass_biz_uniform_classes> uniform_classes__provisioner;
    private readonly Lazy<TClass_biz_uniform_option_categories> uniform_option_categories__provisioner;
    private readonly Lazy<TClass_biz_uniform_piece_colors> uniform_piece_colors__provisioner;
    private readonly Lazy<TClass_biz_uniform_piece_makes> uniform_piece_makes__provisioner;
    private readonly Lazy<TClass_biz_uniform_piece_models> uniform_piece_models__provisioner;
    private readonly Lazy<TClass_biz_uniform_piece_vendors> uniform_piece_vendors__provisioner;
    private readonly Lazy<TClass_biz_uniform_pieces> uniform_pieces__provisioner;
    private readonly Lazy<TClass_biz_uniform_priorities> uniform_priorities__provisioner;
    private readonly Lazy<TClass_biz_user> user__provisioner;
    private readonly Lazy<TClass_biz_user_member_map> user_member_map__provisioner;
    private readonly Lazy<TClass_biz_users> users__provisioner;
    private readonly Lazy<TClass_biz_vehicles> vehicles__provisioner;
    private readonly Lazy<TClass_biz_vehicle_down_natures> vehicle_down_natures__provisioner;
    private readonly Lazy<TClass_biz_vehicle_kinds> vehicle_kinds__provisioner;
    private readonly Lazy<TClass_biz_vehicle_quarters> vehicle_quarters__provisioner;
    private readonly Lazy<TClass_biz_vehicle_quarters_history> vehicle_quarters_history__provisioner;
    private readonly Lazy<TClass_biz_vehicle_usability_history> vehicle_usability_history__provisioner;
    private readonly Lazy<TClass_db__information_schema> db__information_schema__provisioner;
    private readonly Lazy<TClass_db_agencies> db_agencies__provisioner;
    private readonly Lazy<TClass_db_accounts> db_accounts__provisioner;
    private readonly Lazy<TClass_db_agency_satellite_stations> db_agency_satellite_stations__provisioner;
    private readonly Lazy<TClass_db_availabilities> db_availabilities__provisioner;
    private readonly Lazy<TClass_db_capcode_unit_maps> db_capcode_unit_maps__provisioner;
    private readonly Lazy<TClass_db_care_skill_ratings> db_care_skill_ratings__provisioner;
    private readonly Lazy<TClass_db_care_skills> db_care_skills__provisioner;
    private readonly Lazy<TClass_db_chassis_makes> db_chassis_makes__provisioner;
    private readonly Lazy<TClass_db_chassis_models> db_chassis_models__provisioner;
    private readonly Lazy<TClass_db_cities> db_cities__provisioner;
    private readonly Lazy<TClass_db_crew_shift_vehicles> db_crew_shift_vehicles__provisioner;
    private readonly Lazy<TClass_db_custom_makes> db_custom_makes__provisioner;
    private readonly Lazy<TClass_db_custom_models> db_custom_models__provisioner;
    private readonly Lazy<TClass_db_data_conditions> db_data_conditions__provisioner;
    private readonly Lazy<TClass_db_donations> db_donations__provisioner;
    private readonly Lazy<TClass_db_driver_skill_ratings> db_driver_skill_ratings__provisioner;
    private readonly Lazy<TClass_db_driver_skills> db_driver_skills__provisioner;
    private readonly Lazy<TClass_db_efficipay_dockets> db_efficipay_dockets__provisioner;
    private readonly Lazy<TClass_db_efficipay_tokens> db_efficipay_tokens__provisioner;
    private readonly Lazy<TClass_db_enrollment> db_enrollment__provisioner;
    private readonly Lazy<TClass_db_ephemeral_dispatches> db_ephemeral_dispatches__provisioner;
    private readonly Lazy<TClass_db_eval_statuses> db_eval_statuses__provisioner;
    private readonly Lazy<TClass_db_evals> db_evals__provisioner;
    private readonly Lazy<TClass_db_field_situations> db_field_situations__provisioner;
    private readonly Lazy<TClass_db_fuels> db_fuels__provisioner;
    private readonly Lazy<TClass_db_gripes> db_gripes__provisioner;
    private readonly Lazy<TClass_db_incident_nature_translations> db_incident_nature_translations__provisioner;
    private readonly Lazy<TClass_db_incident_natures> db_incident_natures__provisioner;
    private readonly Lazy<TClass_db_indicator_median_length_of_service> db_indicator_median_length_of_service__provisioner;
    private readonly Lazy<TClass_db_indicator_monthly_vehicles_up_and_current> db_indicator_monthly_vehicles_up_and_current__provisioner;
    private readonly Lazy<TClass_db_indicator_shiftwise_vehicles_up_and_current> db_indicator_shiftwise_vehicles_up_and_current__provisioner;
    private readonly Lazy<TClass_db_leaves> db_leaves__provisioner;
    private readonly Lazy<TClass_db_love_letter_batches> db_love_letter_batches__provisioner;
    private readonly Lazy<TClass_db_manifest> db_manifest__provisioner;
    private readonly Lazy<TClass_db_medical_aspirational_phases> db_medical_aspirational_phases__provisioner;
    private readonly Lazy<TClass_db_medical_release_levels> db_medical_release_levels__provisioner;
    private readonly Lazy<TClass_db_members> db_members__provisioner;
    private readonly Lazy<TClass_db_milestones> db_milestones__provisioner;
    private readonly Lazy<TClass_db_notifications> db_notifications__provisioner;
    private readonly Lazy<TClass_db_oscalert_logs> db_oscalert_logs__provisioner;
    private readonly Lazy<TClass_db_patient_age_units> db_patient_age_units__provisioner;
    private readonly Lazy<TClass_db_patient_encounter_levels> db_patient_encounter_levels__provisioner;
    private readonly Lazy<TClass_db_patient_encounters> db_patient_encounters__provisioner;
    private readonly Lazy<TClass_db_post_cardinalities> db_post_cardinalities__provisioner;
    private readonly Lazy<TClass_db_privileges> db_privileges__provisioner;
    private readonly Lazy<TClass_db_radio_dispatches> db_radio_dispatches__provisioner;
    private readonly Lazy<TClass_db_rank_groups> db_rank_groups__provisioner;
    private readonly Lazy<TClass_db_ranks> db_ranks__provisioner;
    private readonly Lazy<TClass_db_residents> db_residents__provisioner;
    private readonly Lazy<TClass_db_role_member_map_logs> db_role_member_map_logs__provisioner;
    private readonly Lazy<TClass_db_role_member_map> db_role_member_map__provisioner;
    private readonly Lazy<TClass_db_role_notification_map> db_role_notification_map__provisioner;
    private readonly Lazy<TClass_db_role_privilege_map> db_role_privilege_map__provisioner;
    private readonly Lazy<TClass_db_roles> db_roles__provisioner;
    private readonly Lazy<TClass_db_scenes_reached> db_scenes_reached__provisioner;
    private readonly Lazy<TClass_db_schedule_assignment_logs> db_schedule_assignment_logs__provisioner;
    private readonly Lazy<TClass_db_schedule_assignments> db_schedule_assignments__provisioner;
    private readonly Lazy<TClass_db_shifts> db_shifts__provisioner;
    private readonly Lazy<TClass_db_skill_ratings> db_skill_ratings__provisioner;
    private readonly Lazy<TClass_db_sms_gateways> db_sms_gateways__provisioner;
    private readonly Lazy<TClass_db_states> db_states__provisioner;
    private readonly Lazy<TClass_db_streets> db_streets__provisioner;
    private readonly Lazy<TClass_db_subjoined_attributes> db_subjoined_attributes__provisioner;
    private readonly Lazy<TClass_db_tapouts> db_tapouts__provisioner;
    private readonly Lazy<TClass_db_tiers> db_tiers__provisioner;
    private readonly Lazy<TClass_db_trespasses> db_trespasses__provisioner;
    private readonly Lazy<TClass_db_uniform_catalogs> db_uniform_catalogs__provisioner;
    private readonly Lazy<TClass_db_uniform_classes> db_uniform_classes__provisioner;
    private readonly Lazy<TClass_db_uniform_option_categories> db_uniform_option_categories__provisioner;
    private readonly Lazy<TClass_db_uniform_piece_colors> db_uniform_piece_colors__provisioner;
    private readonly Lazy<TClass_db_uniform_piece_makes> db_uniform_piece_makes__provisioner;
    private readonly Lazy<TClass_db_uniform_piece_models> db_uniform_piece_models__provisioner;
    private readonly Lazy<TClass_db_uniform_piece_vendors> db_uniform_piece_vendors__provisioner;
    private readonly Lazy<TClass_db_uniform_pieces> db_uniform_pieces__provisioner;
    private readonly Lazy<TClass_db_uniform_priorities> db_uniform_priorities__provisioner;
    private readonly Lazy<TClass_db_user_member_map> db_user_member_map__provisioner;
    private readonly Lazy<TClass_db_user> db_user__provisioner;
    private readonly Lazy<TClass_db_users> db_users__provisioner;
    private readonly Lazy<TClass_db_vehicle_down_natures> db_vehicle_down_natures__provisioner;
    private readonly Lazy<TClass_db_vehicle_kinds> db_vehicle_kinds__provisioner;
    private readonly Lazy<TClass_db_vehicle_quarters_history> db_vehicle_quarters_history__provisioner;
    private readonly Lazy<TClass_db_vehicle_quarters> db_vehicle_quarters__provisioner;
    private readonly Lazy<TClass_db_vehicle_usability_history> db_vehicle_usability_history__provisioner;
    private readonly Lazy<TClass_db_vehicles> db_vehicles__provisioner;
    private readonly Lazy<TClass_db_trail> db_trail__provisioner;
    private readonly Lazy<TClass_dbhomedb_trail> dbhomedb_trail__provisioner;
    private readonly Lazy<TClass_dbkeyclick_trail> dbkeyclick_trail__provisioner;

    }
  }
