using Class_biz__information_schema;
using Class_biz_accounts;
using Class_biz_agencies;
using Class_biz_agency_satellite_stations;
using Class_biz_availabilities;
using Class_biz_capcode_unit_maps;
using Class_biz_care_skill_ratings;
using Class_biz_care_skills;
using Class_biz_chassis_makes;
using Class_biz_chassis_models;
using Class_biz_cities;
using Class_biz_crew_shift_vehicles;
using Class_biz_crews;
using Class_biz_custom_makes;
using Class_biz_custom_models;
using Class_biz_donations;
using Class_biz_driver_skill_ratings;
using Class_biz_driver_skills;
using Class_biz_efficipay_dockets;
using Class_biz_efficipay_tokens;
using Class_biz_enrollment;
using Class_biz_ephemeral_dispatches;
using Class_biz_eval_statuses;
using Class_biz_evals;
using Class_biz_field_situations;
using Class_biz_fleetman;
using Class_biz_fuels;
using Class_biz_fund_drives;
using Class_biz_gripes;
using Class_biz_incident_nature_translations;
using Class_biz_incident_natures;
using Class_biz_indicator_median_length_of_service;
using Class_biz_indicator_monthly_vehicles_up_and_current;
using Class_biz_indicator_shiftwise_vehicles_up_and_current;
using Class_biz_leave;
using Class_biz_leaves;
using Class_biz_love_letter_batches;
using Class_biz_manifest;
using Class_biz_medical_aspirational_phases;
using Class_biz_medical_release_levels;
using Class_biz_members;
using Class_biz_milestones;
using Class_biz_notifications;
using Class_biz_oscalert_logs;
using Class_biz_patient_age_units;
using Class_biz_patient_encounter_levels;
using Class_biz_patient_encounters;
using Class_biz_post_cardinalities;
using Class_biz_privileges;
using Class_biz_publicity;
using Class_biz_quick_messages;
using Class_biz_radio_dispatches;
using Class_biz_rank_groups;
using Class_biz_ranks;
using Class_biz_residents;
using Class_biz_role_member_map;
using Class_biz_role_member_map_logs;
using Class_biz_role_notification_map;
using Class_biz_role_privilege_map;
using Class_biz_roles;
using Class_biz_scenes_reached_distributor;
using Class_biz_schedule_assignment_logs;
using Class_biz_schedule_assignments;
using Class_biz_scheduled_tasks;
using Class_biz_scheduling;
using Class_biz_sections;
using Class_biz_shifts;
using Class_biz_skill_ratings;
using Class_biz_sms_gateways;
using Class_biz_states;
using Class_biz_streets;
using Class_biz_subjoined_attributes;
using Class_biz_tapouts;
using Class_biz_tiers;
using Class_biz_trespasses;
using Class_biz_uniform_catalogs;
using Class_biz_uniform_classes;
using Class_biz_uniform_option_categories;
using Class_biz_uniform_piece_colors;
using Class_biz_uniform_piece_makes;
using Class_biz_uniform_piece_models;
using Class_biz_uniform_piece_vendors;
using Class_biz_uniform_pieces;
using Class_biz_uniform_priorities;
using Class_biz_user;
using Class_biz_user_member_map;
using Class_biz_users;
using Class_biz_vehicle_down_natures;
using Class_biz_vehicle_kinds;
using Class_biz_vehicle_quarters;
using Class_biz_vehicle_quarters_history;
using Class_biz_vehicle_usability_history;
using Class_biz_vehicles;

namespace OscarDotNet.Engine.Di
  {
  public partial class Biz
    {

    //
    // This class is the root of the applications's lazy-loaded composition.
    //

    public TClass_biz__information_schema _information_schema => _information_schema__provisioner.Value;
    public TClass_biz_accounts accounts => accounts__provisioner.Value;
    public TClass_biz_agencies agencies => agencies__provisioner.Value;
    public TClass_biz_agency_satellite_stations agency_satellite_stations => agency_satellite_stations__provisioner.Value;
    public TClass_biz_availabilities availabilities => availabilities__provisioner.Value;
    public TClass_biz_capcode_unit_maps capcode_unit_maps => capcode_unit_maps__provisioner.Value;
    public TClass_biz_care_skills care_skills => care_skills__provisioner.Value;
    public TClass_biz_care_skill_ratings care_skill_ratings => care_skill_ratings__provisioner.Value;
    public TClass_biz_chassis_makes chassis_makes => chassis_makes__provisioner.Value;
    public TClass_biz_chassis_models chassis_models => chassis_models__provisioner.Value;
    public TClass_biz_cities cities => cities__provisioner.Value;
    public TClass_biz_crew_shift_vehicles crew_shift_vehicles => crew_shift_vehicles__provisioner.Value;
    public TClass_biz_crews crews => crews__provisioner.Value;
    public TClass_biz_custom_makes custom_makes => custom_makes__provisioner.Value;
    public TClass_biz_custom_models custom_models => custom_models__provisioner.Value;
    public TClass_biz_donations donations => donations__provisioner.Value;
    public TClass_biz_driver_skills driver_skills => driver_skills__provisioner.Value;
    public TClass_biz_driver_skill_ratings driver_skill_ratings => driver_skill_ratings__provisioner.Value;
    public TClass_biz_efficipay_dockets efficipay_dockets => efficipay_dockets__provisioner.Value;
    public TClass_biz_efficipay_tokens efficipay_tokens => efficipay_tokens__provisioner.Value;
    public TClass_biz_enrollment enrollment => enrollment__provisioner.Value;
    public TClass_biz_ephemeral_dispatches ephemeral_dispatches => ephemeral_dispatches__provisioner.Value;
    public TClass_biz_evals evals => evals__provisioner.Value;
    public TClass_biz_eval_statuses eval_statuses => eval_statuses__provisioner.Value;
    public TClass_biz_field_situations field_situations => field_situations__provisioner.Value;
    public TClass_biz_fleetman fleetman => fleetman__provisioner.Value;
    public TClass_biz_fuels fuels => fuels__provisioner.Value;
    public TClass_biz_fund_drives fund_drives => fund_drives__provisioner.Value;
    public TClass_biz_gripes gripes => gripes__provisioner.Value;
    public TClass_biz_incident_nature_translations incident_nature_translations => incident_nature_translations__provisioner.Value;
    public TClass_biz_incident_natures incident_natures => incident_natures__provisioner.Value;
    public TClass_biz_indicator_median_length_of_service indicator_median_length_of_service => indicator_median_length_of_service__provisioner.Value;
    public TClass_biz_indicator_monthly_vehicles_up_and_current indicator_monthly_vehicles_up_and_current => indicator_monthly_vehicles_up_and_current__provisioner.Value;
    public TClass_biz_indicator_shiftwise_vehicles_up_and_current indicator_shiftwise_vehicles_up_and_current => indicator_shiftwise_vehicles_up_and_current__provisioner.Value;
    public TClass_biz_leave leave => leave__provisioner.Value;
    public TClass_biz_leaves leaves => leaves__provisioner.Value;
    public TClass_biz_love_letter_batches love_letter_batches => love_letter_batches__provisioner.Value;
    public TClass_biz_manifest manifest => manifest__provisioner.Value;
    public TClass_biz_medical_aspirational_phases medical_aspirational_phases => medical_aspirational_phases__provisioner.Value;
    public TClass_biz_medical_release_levels medical_release_levels => medical_release_levels__provisioner.Value;
    public TClass_biz_members members => members__provisioner.Value;
    public TClass_biz_milestones milestones => milestones__provisioner.Value;
    public TClass_biz_notifications notifications => notifications__provisioner.Value;
    public TClass_biz_oscalert_logs oscalert_logs => oscalert_logs__provisioner.Value;
    public TClass_biz_patient_age_units patient_age_units => patient_age_units__provisioner.Value;
    public TClass_biz_patient_encounters patient_encounters => patient_encounters__provisioner.Value;
    public TClass_biz_patient_encounter_levels patient_encounter_levels => patient_encounter_levels__provisioner.Value;
    public TClass_biz_post_cardinalities post_cardinalities => post_cardinalities__provisioner.Value;
    public TClass_biz_privileges privileges => privileges__provisioner.Value;
    public TClass_biz_publicity publicity => publicity__provisioner.Value;
    public TClass_biz_quick_messages quick_messages => quick_messages__provisioner.Value;
    public TClass_biz_ranks ranks => ranks__provisioner.Value;
    public TClass_biz_rank_groups rank_groups => rank_groups__provisioner.Value;
    public TClass_biz_radio_dispatches radio_dispatches => radio_dispatches__provisioner.Value;
    public TClass_biz_residents residents => residents__provisioner.Value;
    public TClass_biz_roles roles => roles__provisioner.Value;
    public TClass_biz_role_member_map role_member_map => role_member_map__provisioner.Value;
    public TClass_biz_role_member_map_logs role_member_map_logs => role_member_map_logs__provisioner.Value;
    public TClass_biz_role_notification_map role_notification_map => role_notification_map__provisioner.Value;
    public TClass_biz_role_privilege_map role_privilege_map => role_privilege_map__provisioner.Value;
    public TClass_biz_scenes_reached_distributor scenes_reached_distributor => scenes_reached_distributor__provisioner.Value;
    public TClass_biz_scheduled_tasks scheduled_tasks => scheduled_tasks__provisioner.Value;
    public TClass_biz_schedule_assignments schedule_assignments => schedule_assignments__provisioner.Value;
    public TClass_biz_schedule_assignment_logs schedule_assignment_logs => schedule_assignment_logs__provisioner.Value;
    public TClass_biz_scheduling scheduling => scheduling__provisioner.Value;
    public TClass_biz_sections sections => sections__provisioner.Value;
    public TClass_biz_shifts shifts => shifts__provisioner.Value;
    public TClass_biz_skill_ratings skill_ratings => skill_ratings__provisioner.Value;
    public TClass_biz_sms_gateways sms_gateways => sms_gateways__provisioner.Value;
    public TClass_biz_states states => states__provisioner.Value;
    public TClass_biz_streets streets => streets__provisioner.Value;
    public TClass_biz_subjoined_attributes subjoined_attributes => subjoined_attributes__provisioner.Value;
    public TClass_biz_tapouts tapouts => tapouts__provisioner.Value;
    public TClass_biz_tiers tiers => tiers__provisioner.Value;
    public TClass_biz_trespasses trespasses => trespasses__provisioner.Value;
    public TClass_biz_uniform_catalogs uniform_catalogs => uniform_catalogs__provisioner.Value;
    public TClass_biz_uniform_classes uniform_classes => uniform_classes__provisioner.Value;
    public TClass_biz_uniform_option_categories uniform_option_categories => uniform_option_categories__provisioner.Value;
    public TClass_biz_uniform_piece_colors uniform_piece_colors => uniform_piece_colors__provisioner.Value;
    public TClass_biz_uniform_piece_makes uniform_piece_makes => uniform_piece_makes__provisioner.Value;
    public TClass_biz_uniform_piece_models uniform_piece_models => uniform_piece_models__provisioner.Value;
    public TClass_biz_uniform_piece_vendors uniform_piece_vendors => uniform_piece_vendors__provisioner.Value;
    public TClass_biz_uniform_pieces uniform_pieces => uniform_pieces__provisioner.Value;
    public TClass_biz_uniform_priorities uniform_priorities => uniform_priorities__provisioner.Value;
    public TClass_biz_user user => user__provisioner.Value;
    public TClass_biz_user_member_map user_member_map => user_member_map__provisioner.Value;
    public TClass_biz_users users => users__provisioner.Value;
    public TClass_biz_vehicles vehicles => vehicles__provisioner.Value;
    public TClass_biz_vehicle_down_natures vehicle_down_natures => vehicle_down_natures__provisioner.Value;
    public TClass_biz_vehicle_kinds vehicle_kinds => vehicle_kinds__provisioner.Value;
    public TClass_biz_vehicle_quarters vehicle_quarters => vehicle_quarters__provisioner.Value;
    public TClass_biz_vehicle_quarters_history vehicle_quarters_history => vehicle_quarters_history__provisioner.Value;
    public TClass_biz_vehicle_usability_history vehicle_usability_history => vehicle_usability_history__provisioner.Value;

    }
  }
